# Generated by Django 2.2.15 on 2020-08-06 18:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(blank=True, max_length=250, null=True)),
                ('training_status', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField(blank=True, max_length=250, null=True)),
                ('end_date', models.DateField(blank=True, max_length=250, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=250, null=True)),
                ('trainer_comments', models.CharField(blank=True, max_length=250, null=True)),
                ('trainer_rating', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(blank=True, max_length=250, null=True)),
                ('prospect_type', models.CharField(blank=True, max_length=250, null=True)),
                ('comments', models.CharField(blank=True, max_length=250, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=250, null=True)),
                ('vendor', models.CharField(blank=True, max_length=250, null=True)),
                ('vendor_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField(blank=True, max_length=250, null=True)),
                ('end_date', models.DateField(blank=True, max_length=250, null=True)),
                ('client_address', models.CharField(blank=True, max_length=250, null=True)),
                ('client_city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Client City, State')),
                ('technology', models.CharField(blank=True, max_length=250, null=True)),
                ('job_title', models.CharField(blank=True, max_length=250, null=True)),
                ('rate', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorces', 'Divorces'), ('Other', 'Other')], max_length=10)),
                ('anniversary_date', models.DateField()),
                ('personal_email', models.EmailField(max_length=254)),
                ('marketing_email', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('country', models.CharField(default='USA', max_length=20)),
                ('immigration_status', models.CharField(choices=[('Opt', 'Opt'), ('CPT', 'CPT'), ('H1B', 'H1B'), ('H4Ead', 'H4Ead'), ('GC-EAD', 'GC -EAD'), ('Grean_Card', 'Green Card'), ('Citizen', 'Citizen'), ('TN', 'TN'), ('Other', 'Other')], max_length=20)),
                ('i_status', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='I-140 Status')),
                ('gc_priority_date', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('Banking&Finance', 'Banking & Finance'), ('Insurance', 'Insurance'), ('Government', 'Government'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Automobile', 'Automobile'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_num', models.CharField(max_length=15)),
                ('official_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('official_phone_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('employee_type', models.CharField(choices=[('W-2_Full_Time_Employee', 'W-2 Full Time Employee'), ('1099-Independent_Contractor', '1099- Independent Contractor'), ('Intern', 'Intern'), ('Subcontractor', 'Subcontractor'), ('Temp_Employee', 'Temp Employee'), ('Vacation', 'Vacation')], max_length=50)),
                ('date_of_joining', models.DateField()),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(max_length=11, verbose_name='SSN')),
                ('technology', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('seniority_level', models.CharField(choices=[('Associate', 'Associate'), ('Consultant', 'Consultant'), ('Senior_Consultant', 'Senior Consultant'), ('Manager', 'Manager'), ('Senior_Manager', 'Senior Manager')], max_length=50)),
                ('employee_status', models.CharField(choices=[('On-Project', 'On-Project'), ('T&P', 'T&P'), ('Prospect', 'Prospect'), ('Bench', 'Bench'), ('Terminated', 'Terminated')], max_length=50)),
                ('date_of_termination', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_terms', models.CharField(max_length=250)),
                ('invoice_contact_name', models.CharField(max_length=250)),
                ('invoice_contact_email', models.CharField(max_length=250)),
                ('invoice_contact_address', models.CharField(max_length=250)),
                ('invoicing_company', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Bill Rate /hr')),
                ('monthly_bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('annual_bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Pay Rate /hr')),
                ('monthly_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('annual_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('perDm', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('federal_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('state_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('extra_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('immigration_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('four_o_one_k', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='401 K')),
                ('total_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('recruiter_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BenchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('visa', models.CharField(blank=True, max_length=250, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('bench_days', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
